package com.nit.cj_exception_handling;

public class Finally_With_Break_Continue_Stmt_1 {

/**	public static void main(String[] args) {

		System.out.println(m1(5));

	}

	static int m1(int a) {

		while (a == 5) {

			try {
				return 10;

			} finally {
				break;
			}

		}
		return 20;

	}
*/
}
